import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Footer from "@/components/Shared/Footer/Footer";
import MainNavbar from "@/components/Shared/Navbar/MainNavbar";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import LocaleHTMLSetter from "@/components/Providers/LocaleHTML";
import SocketProvider from "@/components/Providers/SocketProvider";

// English fonts

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   weight: ["400", "600"],
// });

// Bangla font
const notoBengali = Noto_Sans_Bengali({
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-bengali",
});
export const metadata: Metadata = {
  title: "Task Din",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  // Check if locale exists
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // const fontClass = locale === "bn" ? notoBengali.variable : geistMono.variable;

  return (
    <>
      <LocaleHTMLSetter locale={locale} fontClass={notoBengali.variable} />
      <NextIntlClientProvider>
        <Toaster richColors />
        <NextTopLoader color="#ff4500" height={4} showSpinner={false} />
        <MainNavbar />
        <SocketProvider>{children}</SocketProvider>
        <Footer />
      </NextIntlClientProvider>
    </>
  );
}
